name: Bun CI

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
            - development

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                bun-version: latest
        
        steps:
            - uses: actions/checkout@v4
            -   name: Use Bun
                uses: oven-sh/setup-bun@v1
                with:
                    bun-version: ${{ matrix.bun-version }}

            - run: bun install
            -   name: Run linter
                run: bun biome ci --formatter-enabled=false ./app

            -   name: Run tests
                run: bun test --coverage --bail
